[application]
name = "windns"
default_platform = "desktop"

[desktop]
title = "Windows DNS Switcher"
width = 600
height = 700
resizable = true

[bundle]
identifier = "com.github.arenahito.windns"
publisher = "arenahito"
icon = ["icons/icon.ico"]
